functions: deduplicate add_checked_modules_from_symbol and add_all_modules_from_symbol
Use `add_all_modules_from_symbol` and simply check if it is called
from `add_checked_modules_from_symbol`

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -1211,30 +1211,32 @@ find_module_from_symbol() {
 }
 
 add_all_modules_from_symbol() {
-    local -a mods
+    local symbol="$1"
+    local -a mods paths=("${@:2}")
 
-    mapfile -t mods < <(find_module_from_symbol "$@")
-    (( ${#mods[@]} )) || return 1
-    map add_module "${mods[@]}"
-}
-
-add_checked_modules_from_symbol() {
-    local -a mods
-
-    mapfile -t mods < <(find_module_from_symbol "$@")
+    mapfile -t mods < <(find_module_from_symbol "$symbol" "${paths[@]}")
     (( ${#mods[@]} )) || return 1
 
-    # _autodetect_cache is declared in mkinitcpio and assigned in install/autodetect
-    # shellcheck disable=SC2154
-    if (( ${#_autodetect_cache[@]} )); then
-        mapfile -t mods < <(grep -xFf <(printf '%s\n' "${!_autodetect_cache[@]}") <<<"${mods[@]}")
-        # Do not fail if no autodetected module has the symbol
-        if (( ${#mods[@]} )); then
-            return 0
+    # add_checked_modules_from_symbol
+    if [[ "${FUNCNAME[1]}" == 'add_checked_modules_from_symbol' ]]; then
+        # _autodetect_cache is declared in mkinitcpio and assigned in install/autodetect
+        # shellcheck disable=SC2154
+        if (( ${#_autodetect_cache[@]} )); then
+            mapfile -t mods < <(grep -xFf <(printf '%s\n' "${!_autodetect_cache[@]}") <<<"${mods[@]}")
+            # Do not fail if no autodetected module has the symbol
+            if (( ${#mods[@]} )); then
+                return 0
+            fi
         fi
     fi
 
     map add_module "${mods[@]}"
+}
+
+add_checked_modules_from_symbol() {
+    if ! add_all_modules_from_symbol "$@"; then
+        return 1
+    fi
 }
 
 # vim: set ft=sh ts=4 sw=4 et:
