functions: support staging an early image in the buildroot
This splits the buildroot into two dirs: early and root. early is used
for things that should be loaded before the initramfs, like microcode.
root is the same as it was before.

because of the logic changes in the function, initialize_buildroot no
longer unconditionally creates a working directory in /tmp.

test cases for initialize_buildroot are also added.

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -958,19 +958,27 @@ initialize_buildroot() {
     # creates a temporary directory for the buildroot and initialize it with a
     # basic set of necessary directories and symlinks
 
-    local workdir='' kernver="$1" arch buildroot osreleasefile
+    local kernver="$1" workdir="$2" arch buildroot osreleasefile
     arch="$(uname -m)"
 
-    if ! workdir="$(mktemp -d --tmpdir mkinitcpio.XXXXXX)"; then
-        error 'Failed to create temporary working directory in %s' "${TMPDIR:-/tmp}"
-        return 1
+    if [[ -z "$workdir" ]]; then
+        if ! workdir="$(mktemp -d --tmpdir mkinitcpio.XXXXXX 2>/dev/null)"; then
+            error 'Failed to create temporary working directory in %s' "${TMPDIR:-/tmp}"
+            return 1
+        fi
     fi
-    buildroot="${2:-$workdir/root}"
+    earlyroot="$workdir/early"
+    buildroot="$workdir/root"
 
-    if [[ ! -w "${2:-$workdir}" ]]; then
-        error 'Unable to write to build root: %s' "$buildroot"
+    if [[ ! -w "$workdir" ]]; then
+        error 'Unable to write to working directory: %s' "$workdir"
         return 1
     fi
+
+    # early root structure
+    install -dm755 "$earlyroot"
+    # this flag file is used by some tools
+    echo 1 > "${earlyroot}/early_cpio"
 
     # base directory structure
     install -dm755 "$buildroot"/{new_root,proc,sys,dev,run,tmp,var,etc,usr/{local{,/bin,/sbin,/lib},lib,bin}}
