functions: fix unhelpful error for binary not found on PATH
with the config:

```
BINARIES=(nonexistant /usr/bin/nonexistant)
```
before:
```
==> ERROR: file not found: ''
==> ERROR: file not found: '/usr/bin/nonexistant'
```
after:
```
==> ERROR: binary not found: 'nonexistant'
==> ERROR: file not found: '/usr/bin/nonexistant'
```

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -745,7 +745,10 @@ add_binary() {
     local line='' regex='' binary='' dest='' mode='' sodep='' resolved='' shebang='' interpreter=''
 
     if [[ "${1:0:1}" != '/' ]]; then
-        binary="$(type -P "$1")"
+        if ! binary="$(type -P "$1")"; then
+            error "binary not found: '%s'" "$1"
+            return 1
+        fi
     else
         binary="$1"
     fi
