Fix various coding style issues

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -3,7 +3,7 @@ auto_modules ()
 {
     aliases=$(find /sys/devices/ -name modalias -exec cat {} \;)
     mods=$(/sbin/modprobe --set-version ${KERNELVERSION} --show-depends -a \
-        $aliases 2>/dev/null | sed 's|insmod \(.*\)|\1|' | grep ${@} | sort -u)
+        ${aliases} 2>/dev/null | sed 's|insmod \(.*\)|\1|' | grep $@ | sort -u)
 
     echo "${mods}"
     [ -z "${mods}" ] && return 1
@@ -12,7 +12,7 @@ auto_modules ()
 
 all_modules ()
 {
-    mods=$(find ${MODULEDIR} -name *.ko 2>/dev/null | grep ${@} | sort -u)
+    mods=$(find ${MODULEDIR} -name *.ko 2>/dev/null | grep $@ | sort -u)
 
     echo "${mods}"
     [ -z "${mods}" ] && return 1
@@ -22,7 +22,7 @@ all_modules ()
 checked_modules ()
 {
     if [ -e "${MODULE_FILE}" ]; then
-        for mod in $(all_modules ${@}); do
+        for mod in $(all_modules $@); do
             if grep "^$(basename ${mod%%\.ko})$" "${MODULE_FILE}" >/dev/null 2>&1; then
                 echo ${mod}
             fi
@@ -33,9 +33,9 @@ checked_modules ()
     fi
 }
 
-msg () { [ "${QUIET}" = "n" ] && echo ${@}; }
-err () { echo "ERROR: ${@}" >&2; }
-die () { echo "FATAL: ${@}" >&2; cleanup; exit 1; }
+msg () { [ "${QUIET}" = "n" ] && echo $}; }
+err () { echo "ERROR: $@" >&2; }
+die () { echo "FATAL: $@" >&2; cleanup; exit 1; }
 
 add_full_dir ()
 {
@@ -155,7 +155,7 @@ add_module ()
         HAS_MODULES="y"
         add_file "${path}" && found=1
     done
-    if [ $found -eq 0 ]; then
+    if [ ${found} -eq 0 ]; then
         err "module '$fil' not found"
     fi
 }
@@ -170,7 +170,7 @@ add_binary ()
 
     dest=""
     if [ $# -eq 2 ]; then
-        dest=$2
+        dest=${2}
     fi
 
     if [ ! -f "${bin}" ]; then
@@ -209,19 +209,19 @@ add_binary ()
 parse_hook ()
 {
     local mod bin fil
-    for mod in $MODULES; do
+    for mod in ${MODULES}; do
         if [ -n "${mod}" ]; then
             add_module "${mod}"
         fi
     done
 
-    for bin in $BINARIES; do
+    for bin in ${BINARIES}; do
         if [ -n "${bin}" ]; then
             add_binary "${bin}"
         fi
     done
 
-    for fil in $FILES; do
+    for fil in ${FILES}; do
         if [ -n "${fil}" ]; then
             add_file "${fil}"
         fi
diff --git a/mkinitcpio b/mkinitcpio
--- a/mkinitcpio
+++ b/mkinitcpio
@@ -74,19 +74,19 @@ trap sighandler TERM INT
 
 while getopts ':c:k:s:b:g:a:p:m:vH:LMhS:' arg; do
     if [ "${OPTARG:0:1}" = "-" ]; then
-        echo "error: optional argument to '-$arg' begins with a '-'"
+        echo "error: optional argument to '-${arg}' begins with a '-'"
         echo "  you probably don't want this....aborting."
         usage
     fi
-    case "$arg" in
-        c) CONFIG="$OPTARG" ;;
-        k) KERNELVERSION="$OPTARG" ;;
-        s) SAVELIST="y"; FILELIST="$OPTARG" ;;
-        b) BASEDIR="$OPTARG" ;;
-        g) GENIMG="$OPTARG" ;;
-        a) APPEND="y"; SAVELIST="y"; FILELIST="$OPTARG" ;;
-        p) PRESET="$OPTARG" ;;
-        m) MESSAGE="$OPTARG" ;;
+    case "${arg}" in
+        c) CONFIG="${OPTARG}" ;;
+        k) KERNELVERSION="${OPTARG}" ;;
+        s) SAVELIST="y"; FILELIST="${OPTARG}" ;;
+        b) BASEDIR="${OPTARG}" ;;
+        g) GENIMG="${OPTARG}" ;;
+        a) APPEND="y"; SAVELIST="y"; FILELIST="${OPTARG}" ;;
+        p) PRESET="${OPTARG}" ;;
+        m) MESSAGE="${OPTARG}" ;;
         v) QUIET="n" ;;
         S) SKIPHOOKS="${OPTARG}" ;;
         H) source "${INSTDIR}/${OPTARG}";
@@ -103,10 +103,10 @@ while getopts ':c:k:s:b:g:a:p:m:vH:LMhS:' arg; do
         M) SHOW_AUTOMODS="y" ;;
         h|?) usage ;;
         :) echo "${OPTARG} requires a value..."; usage ;;
-        *) echo "invalid argument '$arg'"; usage ;;
+        *) echo "invalid argument '${arg}'"; usage ;;
     esac
 done
-shift $(($OPTIND - 1))
+shift $((${OPTIND} - 1))
 
 # use preset $PRESET
 if [ -n "${PRESET}" ]; then
@@ -225,7 +225,7 @@ echo ":: Begin build"
 #parse 'global' hook, as defined in ${CONFIG}
 parse_hook
 
-for hook in $HOOKS; do
+for hook in ${HOOKS}; do
     echo "${SKIPHOOKS}" | grep -qw ${hook} && continue
     unset MODULES
     unset BINARIES
@@ -269,7 +269,7 @@ if [ "${HAS_MODULES}" == "y" ]; then
 fi
 
 status=0
-if [ -n "$GENIMG" ]; then
+if [ -n "${GENIMG}" ]; then
     echo -n ":: Generating image '${GENIMG}'..."
     sort -u ${FILELIST} > ${FILELIST}.sorted
     mv ${FILELIST}.sorted ${FILELIST}
@@ -290,5 +290,5 @@ fi
 
 cleanup
 
-exit $status
+exit ${status}
 #vim:set ft=sh ts=4 sw=4 noet:
