lsinitcpio: use the image passed to analyze_image
The `analyze_image` function should use the image file passed to it
instead of reading the global "$_image" variable itself.

diff --git a/lsinitcpio b/lsinitcpio
--- a/lsinitcpio
+++ b/lsinitcpio
@@ -121,17 +121,17 @@ analyze_image() {
     # image to ensure that it's in the cache when we decompress. This avoids
     # variance in timing and makes the time spent reading from storage roughly
     # constant.
-    zsize="$(wc -c <"$_image")"
+    zsize="$(wc -c <"$image")"
 
     # calculate compression ratio
     if [[ -n "$_compress" ]]; then
-        decomptime="$(TIMEFORMAT=%R; { time decomp "$_image" >/dev/null; } 2>&1)"
-        fullsize="$(decomp "$_image" | wc -c)"
+        decomptime="$(TIMEFORMAT=%R; { time decomp "$image" >/dev/null; } 2>&1)"
+        fullsize="$(decomp "$image" | wc -c)"
         ratio=".$(( zsize * 1000 / fullsize % 1000 ))"
     fi
 
     # decompress the image since we need to read from it multiple times.
-    decomp "$_image" | bsdtar -C "$workdir" -xf - || die 'Failed to decompress image'
+    decomp "$image" | bsdtar -C "$workdir" -xf - || die 'Failed to decompress image'
 
     modules=("$workdir/usr/lib/modules"/*/kernel/**/*.ko*)
     if [[ -f "${modules[0]}" ]]; then
@@ -159,8 +159,8 @@ analyze_image() {
     explicitmod=("${MODULES[@]}")
 
     # print results
-    imagename=("$_image")
-    [[ -L "$_image" ]] && imagename+=(" -> $(readlink -e "$_image")")
+    imagename=("$image")
+    [[ -L "$image" ]] && imagename+=(" -> $(readlink -e "$image")")
     msg 'Image: %s%s' "${imagename[@]}"
     [[ -n "$version" ]] && msg 'Created with mkinitcpio %s' "$version"
     msg 'Kernel: %s' "${kernver:-unknown}"
