[mkinitcpio] Create UEFI executables
Implement UEFI executable generation in mkinitcpio by utilizing UEFI
stubs provided by systemd/gummiboot.

This allows us to create a unified boot image we can boot from UEFI
with. These are practical for secure boot as we can sign initramfs,
kernel cmdline and the kernel all at once. By utilizing the
BOOT_LOADER_SPECIFICATION we can also drop new images into the correct
patch and have systemd-boot/gummiboot pick up the images.

The code does several things and does a fair amount of guessing to
figure out all the inputs needed.

We use `/etc/kernel/cmdline` to localize the kernel cmdline options we
want for the image. This is inherited from the `kernel-install` hook
system which might double as some form of standard.

We also do a dance to get the correct kernel image. We do a lookup into
/lib/modules and /boot for both versioned and unversioned kernels
(mainly Arch Linux).

There is an attempt to support both 32bit and 64bit lookup paths for the
stub images, but only 64bit is tested.

Gummiboot is also not tested.

https://www.freedesktop.org/software/systemd/man/kernel-install.html

https://systemd.io/BOOT_LOADER_SPECIFICATION/#type-2-efi-unified-kernel-images

Signed-off-by: Morten Linderud <morten@linderud.pw>

diff --git a/mkinitcpio b/mkinitcpio
--- a/mkinitcpio
+++ b/mkinitcpio
@@ -22,6 +22,8 @@ _d_presets=mkinitcpio.d
 # options and runtime data
 _optmoduleroot= _optgenimg=
 _optcompress= _opttargetdir=
+_optosrelease="/usr/lib/os-release"
+_optuefi= _optmicrocode= _optcmdline= _optsplash= _optkernelimage= _optuefistub=
 _optshowautomods=0 _optsavetree=0 _optshowmods=0
 _optquiet=1 _optcolor=1
 _optskiphooks=() _optaddhooks=() _hooks=()  _optpreset=()
@@ -44,6 +46,7 @@ usage: ${0##*/} [options]
   Options:
    -A, --addhooks <hooks>       Add specified hooks, comma separated, to image
    -c, --config <config>        Use alternate config file. (default: /etc/mkinitcpio.conf)
+   -C, --cmdline <cmdline>      Set kernel line. (default content: /etc/kernel/cmdline, /proc/cmdline)
    -g, --generate <path>        Generate cpio image and write to specified path
    -H, --hookhelp <hookname>    Display help for given hook and exit
    -h, --help                   Display this message and exit
@@ -59,6 +62,12 @@ usage: ${0##*/} [options]
    -d, --generatedir <dir>      Write generated image into <dir>
    -t, --builddir <dir>         Use DIR as the temporary build directory
    -D, --hookdir <dir>          Specify where to look for hooks.
+   -U, --uefi <path>            Build EFI image
+   -m, --microcode <path>       Location of microcode for UEFI executable
+   -R, --osrelease <path>       Include os-release (default: /usr/lib/os-release)
+   -l, --splash <path>          Include bitmap splash for UEFI executable
+   -i, --kernelimage <path>     Kernel image for UEFI executable
+   -I, --uefistub <path>        Location of UEFI stub loader
    -V, --version                Display version information and exit
    -v, --verbose                Verbose output (default: no)
    -z, --compress <program>     Use an alternate compressor on the image
@@ -251,6 +260,56 @@ build_image() {
     fi
 }
 
+build_uefi(){
+    set -x
+    local out=$1 microcode=$2 initramfs=$3 cmdline=$4 osrelease=$5 splash=$6 kernelimg=$7 uefistub=$8 errmsg=
+    OBJCOPYARGS=()
+
+    if [[ -z "$uefistub" ]]; then
+        for stub in {/usr,}/lib/systemd/boot/efi/linux{x64,ia32}.efi.stub {/usr,}/lib/gummiboot/linux{x64,ia32}.efi.stub; do
+            if [[ -f "$stub" ]]; then
+                uefistub="$stub"
+                break
+            fi
+        done
+    fi
+
+    if [[ -z "$kernelimg" ]]; then
+        for img in "/lib/modules/$KERNELIMAGE" "/boot/vmlinuz-$KERNELIMAGE" "/boot/vmlinuz-linuz"; do
+            if [[ -f "$img" ]]; then
+                KERNELIMAGE="$img"
+                break
+            fi
+        done
+    fi
+
+    if [[ -z "$cmdline" ]]; then
+        if [[ -f "/etc/kernel/cmdline" ]]; then
+            cmdline="/etc/kernel/cmdline"
+        else
+            cmdline="/proc/cmdline"
+        fi
+    fi
+
+    if [[ -n "$splash" ]]; then
+        OBJCOPYARGS+=("--add-section .splash=$splash --change-section-vma .splash=0x40000")
+    fi
+    msg "Creating EFI image: %s" "$out"
+    objcopy \
+        --add-section .osrel="$osrelease" --change-section-vma .osrel=0x20000 \
+        --add-section .cmdline="$cmdline" --change-section-vma .cmdline=0x30000 \
+        --add-section .linux="$kernelimg" --change-section-vma .linux=0x2000000 \
+        --add-section .initrd=<(cat "$microcode" "$initramfs" ) --change-section-vma .initrd=0x3000000 \
+        ${OBJCOPYARGS[@]} "$uefistub" "$out"
+
+    status=$?
+    if (( $status )) ; then
+        error "EFI image generation FAILED"
+    else
+        msg "EFI image generation successful"
+    fi
+}
+
 process_preset() (
     local preset=$1 preset_image= preset_options=
     local -a preset_mkopts preset_cmd
@@ -307,6 +366,16 @@ process_preset() (
             preset_cmd+=(${!preset_options}) # intentional word splitting
         fi
 
+        preset_efi_image=${p}_efi_image
+        if [[ ${!preset_efi_image:-$ALL_efi_image} ]]; then
+            preset_cmd+=(-U "${!preset_efi_image:-$ALL_efi_image}")
+        fi
+
+        preset_microcode=${p}_microcode
+        if [[ ${!preset_microcode:-$ALL_microcode} ]]; then
+            preset_cmd+=(-m "${!preset_microcode:-$ALL_microcode}")
+        fi
+
         msg2 "${preset_cmd[*]}"
         MKINITCPIO_PROCESS_PRESET=1 "$0" "${preset_cmd[@]}"
         (( $? )) && ret=1
@@ -345,10 +414,11 @@ preload_builtin_modules() {
 trap 'cleanup 130' INT
 trap 'cleanup 143' TERM
 
-_opt_short='A:c:D:g:H:hk:nLMPp:r:S:sd:t:Vvz:'
+_opt_short='A:c:D:g:H:hk:I:i:nLl:Mm:Pp:r:S:sd:t:U:Vvz:'
 _opt_long=('add:' 'addhooks:' 'config:' 'generate:' 'hookdir': 'hookhelp:' 'help'
           'kernel:' 'listhooks' 'automods' 'moduleroot:' 'nocolor' 'allpresets'
-          'preset:' 'skiphooks:' 'save' 'generatedir:' 'builddir:' 'version' 'verbose' 'compress:')
+          'preset:' 'skiphooks:' 'save' 'generatedir:' 'builddir:' 'version' 'verbose' 'compress:'
+          'uefi:' 'microcode:' 'splash:' 'kernelimage:' 'uefistub:')
 
 parseopts "$_opt_short" "${_opt_long[@]}" -- "$@" || exit 1
 set -- "${OPTRET[@]}"
@@ -366,6 +436,10 @@ while :; do
         -c|--config)
             shift
             _f_config=$1
+            ;;
+        -C|--cmdline)
+            shift
+            _optcmdline=$1
             ;;
         -k|--kernel)
             shift
@@ -400,6 +474,13 @@ while :; do
         -n|--nocolor)
             _optcolor=0
             ;;
+        -U|--uefi)
+            shift
+            [[ -d $1 ]] && die "Invalid image path -- must not be a directory"
+            if ! _optuefi=$(readlink -f "$1") || [[ ! -e ${_optgenimg%/*} ]]; then
+                die "Unable to write to path: \`%s'" "$1"
+            fi
+            ;;
         -v|--verbose)
             _optquiet=0
             ;;
@@ -418,12 +499,34 @@ while :; do
             hook_list
             exit 0
             ;;
+        -l|--splash)
+            shift
+            [[ -f $1 ]] || die "Invalid file -- must be a file"
+            _optsplash=$1
+            ;;
+        -i|--kernelimage)
+            shift
+             _optkernelimage=$1
+            ;;
+        -I|--uefistub)
+            shift
+             _optkernelimage=$1
+            ;;
         -M|--automods)
             _optshowautomods=1
+            ;;
+        -m|--microcode)
+            shift
+             _optmicrocode=$1
             ;;
         -P|--allpresets)
             _optpreset=("$_d_presets"/*.preset)
             [[ -e ${_optpreset[0]} ]] || die "No presets found in $_d_presets"
+            ;;
+        -R|--osrelease)
+            shift
+            [[ ! -f $1 ]] && die "Invalid file -- must be a file"
+            _optosrelease=$1
             ;;
         -t|--builddir)
             shift
@@ -554,6 +657,10 @@ elif [[ $_opttargetdir ]]; then
     msg "Build complete."
 else
     msg "Dry run complete, use -g IMAGE to generate a real image"
+fi
+
+if [[ $_optuefi && $_optgenimg ]]; then
+    build_uefi "$_optuefi" "$_optmicrocode" "$_optgenimg" "$_optcmdline" "$_optosrelease" "$_optkernelimage" "$_optsplash" "$_optuefistub"
 fi
 
 cleanup $(( !!_builderrors ))
