install,hook: fix shellcheck errors
Signed-off-by: Morten Linderud <morten@linderud.pw>

diff --git a/hook/encrypt b/hook/encrypt
--- a/hook/encrypt
+++ b/hook/encrypt
@@ -2,18 +2,22 @@
 
 run_hook() {
     modprobe -a -q dm-crypt >/dev/null 2>&1
+    # assigned by parse_cmdline
+    # shellcheck disable=SC2154
     [ "${quiet}" = "y" ] && CSQUIET=">/dev/null"
 
     # Get keyfile if specified
     ckeyfile="/crypto_keyfile.bin"
     if [ -n "$cryptkey" ]; then
-        IFS=: read ckdev ckarg1 ckarg2 <<EOF
+        IFS=: read -r ckdev ckarg1 ckarg2 <<EOF
 $cryptkey
 EOF
 
+        # rootdelay is assigned by parse_cmdline
+        # shellcheck disable=SC2154
         if [ "$ckdev" = "rootfs" ]; then
             ckeyfile=$ckarg1
-        elif resolved=$(resolve_device "${ckdev}" ${rootdelay}); then
+        elif resolved=$(resolve_device "${ckdev}" "${rootdelay}"); then
             case ${ckarg1} in
                 *[!0-9]*)
                     # Use a file on the device
@@ -30,12 +34,12 @@ EOF
                     ;;
             esac
         fi
-        [ ! -f ${ckeyfile} ] && echo "Keyfile could not be opened. Reverting to passphrase."
+        [ ! -f "${ckeyfile}" ] && echo "Keyfile could not be opened. Reverting to passphrase."
     fi
 
     if [ -n "${cryptdevice}" ]; then
         DEPRECATED_CRYPT=0
-        IFS=: read cryptdev cryptname cryptoptions <<EOF
+        IFS=: read -r cryptdev cryptname cryptoptions <<EOF
 $cryptdevice
 EOF
     else
@@ -80,20 +84,20 @@ EOF
     IFS="$OLDIFS"
     unset OLDIFS
 
-    if resolved=$(resolve_device "${cryptdev}" ${rootdelay}); then
-        if cryptsetup isLuks ${resolved} >/dev/null 2>&1; then
-            [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
+    if resolved=$(resolve_device "${cryptdev}" "${rootdelay}"); then
+        if cryptsetup isLuks "${resolved}" >/dev/null 2>&1; then
+            [ "${DEPRECATED_CRYPT}" -eq 1 ] && warn_deprecated
             dopassphrase=1
             # If keyfile exists, try to use that
-            if [ -f ${ckeyfile} ]; then
-                if eval cryptsetup --key-file ${ckeyfile} open --type luks ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; then
+            if [ -f "${ckeyfile}" ]; then
+                if eval cryptsetup --key-file "${ckeyfile}" open --type luks "${resolved}" "${cryptname}" "${cryptargs}" "${CSQUIET}"; then
                     dopassphrase=0
                 else
                     echo "Invalid keyfile. Reverting to passphrase."
                 fi
             fi
             # Ask for a passphrase
-            if [ ${dopassphrase} -gt 0 ]; then
+            if [ "${dopassphrase}" -gt 0 ]; then
                 if command -v plymouth >/dev/null 2>&1 && plymouth --ping 2>/dev/null; then
                     plymouth ask-for-password \
                         --prompt="A password is required to access the ${cryptname} volume" \
@@ -103,13 +107,13 @@ EOF
                     echo "A password is required to access the ${cryptname} volume:"
 
                     #loop until we get a real password
-                    while ! eval cryptsetup open --type luks ${resolved} ${cryptname} ${cryptargs} ${CSQUIET}; do
+                    while ! eval cryptsetup open --type luks "${resolved}" "${cryptname}" "${cryptargs}" "${CSQUIET}"; do
                         sleep 2;
                     done
                 fi
             fi
             if [ -e "/dev/mapper/${cryptname}" ]; then
-                if [ ${DEPRECATED_CRYPT} -eq 1 ]; then
+                if [ "${DEPRECATED_CRYPT}" -eq 1 ]; then
                     export root="/dev/mapper/root"
                 fi
             else
@@ -117,7 +121,7 @@ EOF
                 return 1
             fi
         elif [ -n "${crypto}" ]; then
-            [ ${DEPRECATED_CRYPT} -eq 1 ] && warn_deprecated
+            [ "${DEPRECATED_CRYPT}" -eq 1 ] && warn_deprecated
             msg "Non-LUKS encrypted device found..."
             if echo "$crypto" | awk -F: '{ exit(NF == 5) }'; then
                 err "Verify parameter format: crypto=hash:cipher:keysize:offset:skip"
@@ -125,7 +129,7 @@ EOF
                 return 1
             fi
             exe="cryptsetup open --type plain $resolved $cryptname $cryptargs"
-            IFS=: read c_hash c_cipher c_keysize c_offset c_skip <<EOF
+            IFS=: read -r c_hash c_cipher c_keysize c_offset c_skip <<EOF
 $crypto
 EOF
             [ -n "$c_hash" ]    && exe="$exe --hash '$c_hash'"
@@ -139,15 +143,13 @@ EOF
                 echo ""
                 echo "A password is required to access the ${cryptname} volume:"
             fi
-            eval "$exe $CSQUIET"
-
-            if [ $? -ne 0 ]; then
+            if ! eval "$exe $CSQUIET"; then
                 err "Non-LUKS device decryption failed. verify format: "
                 err "      crypto=hash:cipher:keysize:offset:skip"
                 return 1
             fi
             if [ -e "/dev/mapper/${cryptname}" ]; then
-                if [ ${DEPRECATED_CRYPT} -eq 1 ]; then
+                if [ "${DEPRECATED_CRYPT}" -eq 1 ]; then
                     export root="/dev/mapper/root"
                 fi
             else
@@ -158,7 +160,7 @@ EOF
             err "Failed to open encryption mapping: The device ${cryptdev} is not a LUKS volume and the crypto= paramater was not specified."
         fi
     fi
-    rm -f ${ckeyfile}
+    rm -f "${ckeyfile}"
 }
 
 # vim: set ft=sh ts=4 sw=4 et:
