keymap/consolefont: source rc.conf properly from $BASEDIR
This is partially in response to FS#24685, which should hopefully cut
back on configuration duplication on non-sysvinit systems. This does,
however, also fix a bug with keymap/consolefont pulling the wrong
rc.conf when BASEDIR is not '/' or unset.

Signed-off-by: Dave Reisner <dreisner@archlinux.org>

diff --git a/install/consolefont b/install/consolefont
--- a/install/consolefont
+++ b/install/consolefont
@@ -3,26 +3,30 @@
 build() {
     local file ext
 
-    eval "$(grep -e "^CONSOLEFONT=" /etc/rc.conf)"
-    if [[ -n "$CONSOLEFONT" ]]; then
-        for file in "$BASEDIR/usr/share/kbd/consolefonts/$CONSOLEFONT".psf?(u)?(.gz); do
-            if [[ -e $file ]]; then
-                [[ $file =~ \.(psfu?)(\.gz)?$ ]] && ext=${BASH_REMATCH[1]}
-                if [[ $file = *.gz ]]; then
-                    gzip -cd "$file" > "$BUILDROOT/consolefont.$ext"
-                else
-                    add_file "${file#$BASEDIR}" "/consolefont.$ext"
+    # subshell to avoid namespace pollution
+    (
+        . "$BASEDIR/etc/rc.conf"
+        if [[ -n "$CONSOLEFONT" ]]; then
+            for file in "$BASEDIR/usr/share/kbd/consolefonts/$CONSOLEFONT".psf?(u)?(.gz); do
+                if [[ -e $file ]]; then
+                    [[ $file =~ \.(psfu?)(\.gz)?$ ]] && ext=${BASH_REMATCH[1]}
+                    if [[ $file = *.gz ]]; then
+                        gzip -cd "$file" > "$BUILDROOT/consolefont.$ext"
+                    else
+                        add_file "${file#$BASEDIR}" "/consolefont.$ext"
+                    fi
+                    exit 0
                 fi
-                SCRIPT=consolefont
-                return 0
-            fi
-        done
-        error "consolefont: requested font not found: \`%s'" "$CONSOLEFONT"
-        return 1
-    else
-        warning "consolefont: no font found in %s/etc/rc.conf" "${BASEDIR%/}"
-        return 1
-    fi
+            done
+            error "consolefont: requested font not found: \`%s'" "$CONSOLEFONT"
+            exit 1
+        else
+            warning "consolefont: no font found in %s/etc/rc.conf" "${BASEDIR%/}"
+            exit 1
+        fi
+    )
+
+    (( $? == 0 )) && SCRIPT=consolefont
 }
 
 help() {
